name: sherlock-rag-chatbot
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:

  # --- Conda packages ---
  - python=3.12
  - pytorch
  - python-dotenv
  - sentence-transformers
  - streamlit
  - pandas
  - pip

  # --- Pip packages ---
  - pip:
    - llama-index
    - llama-index-core
    - llama-index-embeddings-huggingface
    - ragas
    - llama-index-llms-groq
